const data = {
    name: "anime",
    fields: [
        {"name": "name", "type": "string" },
        {"name": "description", "type": "string" },
        {"name": "seasons", "type": "int32" },
        {"name": "genre", "type": "auto"},
        {"name": "status", "type": "string"}
    ],
    documents: [
        {
            id: "1",
            name: "Attack on Titan",
            description:
                "In a world where humanity resides within enormous walled cities to protect themselves from Titans, gigantic humanoid creatures.",
            rating: 9.1,
            img: "https://example.com/images/aot.jpg",
            genre: ["Action", "Drama", "Fantasy"],
            aired: "2013-04-07 to 2021-04-04",
            seasons: 4,
            status: "Completed",
            episodes: 75,
            popularity: 10000,
        },
        {
            id: "2",
            name: "My Hero Academia",
            description:
                "In a world where people with superpowers, known as 'quirks', are the norm, a young boy without them still dreams of becoming a hero.",
            rating: 8.5,
            img: "https://example.com/images/mha.jpg",
            genre: ["Action", "Comedy", "Superhero"],
            aired: "2016-04-03 to Present",
            seasons: 5,
            status: "Ongoing",
            episodes: 100,
            popularity: 9500,
        },
        {
            id: "3",
            name: "Demon Slayer: Kimetsu no Yaiba",
            description:
                "Tanjiro Kamado is a kind-hearted boy who becomes a demon slayer to save his sister and avenge his family.",
            rating: 9.2,
            img: "https://example.com/images/demonslayer.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2019-04-06 to 2021-12-05",
            seasons: 2,
            status: "Completed",
            episodes: 26,
            popularity: 12000,
        },
        {
            id: "4",
            name: "One Piece",
            description:
                "The adventures of Monkey D. Luffy and his pirate crew in their quest to find the One Piece and become the Pirate King.",
            rating: 8.6,
            img: "https://example.com/images/onepiece.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "1999-10-20 to Present",
            seasons: 20,
            status: "Ongoing",
            episodes: 1000,
            popularity: 15000,
        },
        {
            id: "5",
            name: "Death Note",
            description:
                "A high school student discovers a supernatural notebook that allows him to kill anyone by writing their name in it.",
            rating: 9.0,
            img: "https://example.com/images/deathnote.jpg",
            genre: ["Mystery", "Psychological", "Thriller"],
            aired: "2006-10-03 to 2007-06-27",
            seasons: 1,
            status: "Completed",
            episodes: 37,
            popularity: 8500,
        },
        {
            id: "6",
            name: "Fullmetal Alchemist: Brotherhood",
            description:
                "Two brothers use alchemy in their quest to find the Philosopher's Stone to restore their bodies after a failed alchemical experiment.",
            rating: 9.2,
            img: "https://example.com/images/fma.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2009-04-05 to 2010-07-04",
            seasons: 1,
            status: "Completed",
            episodes: 64,
            popularity: 9500,
        },
        {
            id: "7",
            name: "Sword Art Online",
            description:
                "Players of a virtual reality MMORPG discover they cannot log out and must clear the game to escape.",
            rating: 7.8,
            img: "https://example.com/images/sao.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2012-07-08 to 2014-09-20",
            seasons: 3,
            status: "Completed",
            episodes: 49,
            popularity: 7000,
        },
        {
            id: "8",
            name: "Naruto",
            description:
                "A young ninja seeks recognition from his peers and dreams of becoming the Hokage, the village leader.",
            rating: 8.3,
            img: "https://example.com/images/naruto.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2002-10-03 to 2007-02-08",
            seasons: 5,
            status: "Completed",
            episodes: 220,
            popularity: 11000,
        },
        {
            id: "9",
            name: "Tokyo Ghoul",
            description:
                "A college student becomes a half-ghoul after a chance encounter and must learn to live among ghouls.",
            rating: 7.9,
            img: "https://example.com/images/tokyoghoul.jpg",
            genre: ["Action", "Horror", "Mystery"],
            aired: "2014-07-04 to 2014-09-19",
            seasons: 2,
            status: "Completed",
            episodes: 24,
            popularity: 8000,
        },
        {
            id: "10",
            name: "Steins;Gate",
            description:
                "A group of friends discovers a way to send messages to the past, leading to unforeseen consequences.",
            rating: 9.1,
            img: "https://example.com/images/steinsgate.jpg",
            genre: ["Sci-Fi", "Thriller"],
            aired: "2011-04-06 to 2011-09-14",
            seasons: 1,
            status: "Completed",
            episodes: 24,
            popularity: 9000,
        },
        {
            id: "11",
            name: "Cowboy Bebop",
            description:
                "Set in the future, it follows bounty hunters traveling through space on their ship, the Bebop.",
            rating: 8.9,
            img: "https://example.com/images/cowboybebop.jpg",
            genre: ["Action", "Adventure", "Sci-Fi"],
            aired: "1998-04-03 to 1999-04-24",
            seasons: 1,
            status: "Completed",
            episodes: 26,
            popularity: 9500,
        },
        {
            id: "12",
            name: "Your Lie in April",
            description:
                "A piano prodigy who lost his ability to hear the sound of his own piano meets a spirited violinist.",
            rating: 8.6,
            img: "https://example.com/images/yourlieinapril.jpg",
            genre: ["Drama", "Romance", "Music"],
            aired: "2014-10-09 to 2015-03-19",
            seasons: 1,
            status: "Completed",
            episodes: 22,
            popularity: 8000,
        },
        {
            id: "13",
            name: "Sword Art Online",
            description:
                "Players of a virtual reality MMORPG discover they cannot log out and must clear the game to escape.",
            rating: 7.8,
            img: "https://example.com/images/swordartonline.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2012-07-08 to 2014-09-20",
            seasons: 3,
            status: "Completed",
            episodes: 49,
            popularity: 7000,
        },
        {
            id: "14",
            name: "My Neighbor Totoro",
            description:
                "Two girls move to the countryside and encounter friendly forest spirits, including Totoro.",
            rating: 8.2,
            img: "https://example.com/images/totoro.jpg",
            genre: ["Fantasy", "Family"],
            aired: "1988",
            seasons: 1,
            status: "Completed",
            episodes: 1,
            popularity: 8500,
        },
        {
            id: "15",
            name: "The Promised Neverland",
            description:
                "Three children at an orphanage discover a dark secret and plan an escape.",
            rating: 8.6,
            img: "https://example.com/images/promisedneverland.jpg",
            genre: ["Mystery", "Thriller", "Drama"],
            aired: "2019-01-11 to 2020-03-26",
            seasons: 2,
            status: "Completed",
            episodes: 24,
            popularity: 8000,
        },
        {
            id: "16",
            name: "Mob Psycho 100",
            description:
                "A young psychic tries to lead a normal life while dealing with spirits and emotions.",
            rating: 8.6,
            img: "https://example.com/images/mobpsycho.jpg",
            genre: ["Action", "Comedy", "Supernatural"],
            aired: "2016-07-11 to 2016-09-26",
            seasons: 3,
            status: "Ongoing",
            episodes: 25,
            popularity: 8500,
        },
        {
            id: "17",
            name: "Vinland Saga",
            description:
                "A young Viking seeks revenge for his father's death during the Viking Age.",
            rating: 9.0,
            img: "https://example.com/images/vinlandsaga.jpg",
            genre: ["Action", "Adventure", "Historical"],
            aired: "2019-07-07 to 2019-12-29",
            seasons: 1,
            status: "Completed",
            episodes: 24,
            popularity: 9000,
        },
        {
            id: "18",
            name: "Kaguya-sama: Love Is War",
            description:
                "Two high school geniuses engage in a battle of wits to make the other confess their love first.",
            rating: 8.9,
            img: "https://example.com/images/kaguyasama.jpg",
            genre: ["Romance", "Comedy", "Slice of Life"],
            aired: "2019-01-12 to 2019-03-30",
            seasons: 3,
            status: "Ongoing",
            episodes: 30,
            popularity: 9500,
        },
        {
            id: "19",
            name: "Re:Zero - Starting Life in Another World",
            description:
                "A boy is transported to another world and discovers he has the ability to return from death.",
            rating: 8.7,
            img: "https://example.com/images/rezero.jpg",
            genre: ["Fantasy", "Drama", "Thriller"],
            aired: "2016-04-04 to 2016-09-19",
            seasons: 2,
            status: "Ongoing",
            episodes: 50,
            popularity: 9000,
        },
        {
            id: "20",
            name: "Made in Abyss",
            description:
                "A young girl descends into a mysterious abyss to find her mother and uncover its secrets.",
            rating: 8.8,
            img: "https://example.com/images/madeinabyss.jpg",
            genre: ["Adventure", "Fantasy", "Mystery"],
            aired: "2017-07-07 to 2017-09-29",
            seasons: 1,
            status: "Completed",
            episodes: 13,
            popularity: 9000,
        },
        {
            id: "21",
            name: "Fairy Tail",
            description:
                "A group of wizards in the Fairy Tail guild take on quests and face powerful enemies.",
            rating: 8.5,
            img: "https://example.com/images/fairytail.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2009-10-12 to 2019-09-29",
            seasons: 9,
            status: "Completed",
            episodes: 328,
            popularity: 12000,
        },
        {
            id: "22",
            name: "Black Clover",
            description:
                "A boy born without magic strives to become the Wizard King in a world filled with magic.",
            rating: 7.9,
            img: "https://example.com/images/blackclover.jpg",
            genre: ["Action", "Adventure", "Fantasy"],
            aired: "2017-10-03 to 2021-03-30",
            seasons: 4,
            status: "Completed",
            episodes: 170,
            popularity: 8000,
        },
        {
            id: "23",
            name: "Yuri!!! on ICE",
            description:
                "A Japanese figure skater finds inspiration and love while training with a famous coach.",
            rating: 8.5,
            img: "https://example.com/images/yurionice.jpg",
            genre: ["Sports", "Drama", "Romance"],
            aired: "2016-10-06 to 2017-04-01",
            seasons: 1,
            status: "Completed",
            episodes: 12,
            popularity: 8500,
        },
        {
            id: "24",
            name: "Toradora!",
            description:
                "A romantic comedy about a high school boy and girl who help each other with their respective crushes.",
            rating: 8.6,
            img: "https://example.com/images/toradora.jpg",
            genre: ["Romance", "Comedy", "Slice of Life"],
            aired: "2008-10-02 to 2009-03-26",
            seasons: 1,
            status: "Completed",
            episodes: 25,
            popularity: 9000,
        },
    ],
};

export default data;
