name: Deployment on web-stage.gtls.store using SSH
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_STAGE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 192.155.110.18 >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          ssh -i ~/.ssh/id_rsa gtls@192.155.110.18 "cd /home/gtls/web-stage.gtls.store && git pull origin main && composer install && npm install && php artisan cache:clear && npm run build"
          echo "Deployment completed."
